### ISSUE TITLE
Rescue NFT Function

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#40]
Unsure if we have this implemented. I remember @DrHongos demo'ing a rescue ETH function. We should also be able to withdraw NFTs that may be stuck or some error with buyout. The DAO should be the only address that could call either of these functions.

**Comment by DrHongos** [comment]
Since we are having troubles with the UI, let me add a different approach to verify this is working ;)
Find the ID of the token (in manage page the structure is https://fraktal-dapp.vercel.app/nft/XX/manage) where XX is the number (ID)
in write contracts (Etherscan) 
https://rinkeby.etherscan.io/address/0xFf3532447a93497471279150602B6ec24ae1170f#writeContract
find the claimFraktal function and call it with the id argument.
This call will fail if you dont have the votes! If any other bug arises, we'll open a specific issue.
